"use client";

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { getBrandIdentity } from '@/app/lib/brandsService';
import { BrandIdentity } from '@/app/lib/types';
import BrandGuidePDF from '@/app/components/BrandGuidePDF';
import { useBrandStore } from '@/app/lib/store';
import { Loader2 } from 'lucide-react';

export default function ClientBrandView() {
    const { id } = useParams();
    const [loading, setLoading] = useState(true);
    const { updateIdentity } = useBrandStore();
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const load = async () => {
            if (!id) return;
            try {
                const data = await getBrandIdentity(id as string);
                if (data) {
                    updateIdentity(data);
                } else {
                    setError("Brand not found or link has expired.");
                }
            } catch (err) {
                setError("Failed to load brand data.");
            } finally {
                setLoading(false);
            }
        };
        load();
    }, [id, updateIdentity]);

    if (loading) {
        return (
            <div className="h-screen w-full flex flex-col items-center justify-center bg-slate-950 text-white">
                <Loader2 className="w-12 h-12 animate-spin text-purple-500 mb-4" />
                <p className="text-slate-400 font-medium animate-pulse">Brand Identity Loading...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="h-screen w-full flex flex-col items-center justify-center bg-slate-950 text-white p-6 text-center">
                <div className="bg-red-500/10 border border-red-500/20 p-8 rounded-2xl max-w-md">
                    <h1 className="text-2xl font-bold mb-2">Access Denied</h1>
                    <p className="text-slate-400">{error}</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-950 py-12 px-4">
            <div className="max-w-4xl mx-auto mb-8 flex justify-between items-center text-slate-400">
                <span className="text-xs font-bold uppercase tracking-widest">Client Preview Mode</span>
                <span className="text-xs">Generated by AI Branding Creator</span>
            </div>
            <BrandGuidePDF />
        </div>
    );
}
